script name chenge

diff --git a/src/migrate_website b/src/migrate_website
--- a/src/migrate_website
+++ b/src/migrate_website
@@ -17,9 +17,9 @@ function get_current_dir()
 function arg_check()
 {
     if [ -z "$INPUT" ]; then
-        echo "[ ERROR ] backup file name missing "
+        echo "  [ ERROR ] backup file name missing "
         echo
-        echo "[ EXAMPLE ] ./migrate.sh backup.tar.gz"
+        echo "  [ EXAMPLE ] ./migrate_website backup.tar.gz"
         echo
         exit 1
     fi
@@ -28,7 +28,7 @@ function arg_check()
 function import_new_config()
 {
     source $CURRENT_DIR/migrate_config.sh
-    [ $? -ne 0 ] && { echo "[ ERROR ] [ ${LINENO} ]"; exit 1;}
+    [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ]"; exit 1;}
 }
 
 function db_empty_check()
@@ -36,7 +36,7 @@ function db_empty_check()
     table_count=$(mysql -u$NEW_DB_USERNAME -p$NEW_DB_PASSWORD -h $NEW_DB_HOST -P $NEW_DB_PORT $NEW_DB_NAME -e "SHOW TABLES;" | wc -l)
 
     if [ $table_count -gt 0 ];then
-        echo "[ ERROR ] [ ${LINENO} ] DB is not empty ( table_count : $table_count ), truncate database before migrating"
+        echo "  [ ERROR ] [ ${LINENO} ] DB is not empty ( table_count : $table_count ), truncate database before migrating"
         echo
         echo "      -> $NEW_DB_NAME"
         echo
@@ -49,7 +49,7 @@ function dir_empty_check()
 {
     file_count=`ls ${NEW_WEBSITE_ROOT_DIR}/ | wc -l`
     if [ $file_count -gt 0 ];then
-        echo "[ ERROR ] [ ${LINENO} ] website root directory is not empty, clear all files before migrating"
+        echo "  [ ERROR ] [ ${LINENO} ] website root directory is not empty, clear all files before migrating"
         echo
         echo "      -> $NEW_WEBSITE_ROOT_DIR"
         echo
@@ -67,11 +67,11 @@ function validate_input()
 
     # GET ABSOLUTE PATH 
     cd $SOURCE_PATH
-    [ $? -ne 0 ] && { echo "[ ERROR ] [ ${LINENO} ]"; exit 1; }
+    [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ]"; exit 1; }
     SOURCE_PATH=`pwd -P`
 
     cd $SOURCE_PATH
-    [ $? -ne 0 ] && { echo "[ ERROR ] [ ${LINENO} ]"; exit 1; }
+    [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ]"; exit 1; }
 
     # EXTRACT FILENAME AND PATH FROM INPUT 
 
@@ -92,13 +92,13 @@ function validate_input()
 
 
     if [ "$EXTN1" != "gz" ]; then
-        echo "[ ERROR ] invalid backup file name ( file name should end with .tar.gz ) "
+        echo "  [ ERROR ] invalid backup file name ( file name should end with .tar.gz ) "
         echo
         exit 1
     fi
 
     if [ "$EXTN2" != "tar" ]; then
-        echo "[ ERROR ] invalid backup file name ( file name should end with .tar.gz ) "
+        echo "  [ ERROR ] invalid backup file name ( file name should end with .tar.gz ) "
         echo
         exit 1
     fi
@@ -122,18 +122,18 @@ function get_user_confirmation()
 function extract_backup_archive()
 {
     echo
-    echo "[ status ] extracting backup file : $SOURCE_FILE"
+    echo "  Extracting backup file : $SOURCE_FILE"
     echo
     # Enter backup directory
     cd $SOURCE_PATH
-    [ $? -ne 0 ] && { echo "[ ERROR ] [ ${LINENO} ]"; exit 1; }
+    [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ]"; exit 1; }
 
     # Remove Old Restore Folder ( if any )
     rm -rf $RESTORE_DIR
 
     # Extract backup archive
     tar -zxvf $SOURCE_FILE 1> /dev/null
-    [ $? -ne 0 ] && { echo "[ ERROR ] [ ${LINENO} ]"; exit 1; }
+    [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ]"; exit 1; }
     echo
 }
 
@@ -141,14 +141,14 @@ function extract_backup_archive()
 function import_old_config()
 {
     source $SOURCE_PATH/$RESTORE_DIR/restore_config.sh
-    [ $? -ne 0 ] && { echo "[ ERROR ] [ ${LINENO} ]"; exit 1; }
+    [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ]"; exit 1; }
 
 }
 
 function print_old_config()
 {
     echo
-    echo "OLD CONFIGURATION"
+    echo "  OLD CONFIGURATION"
     echo
     echo "  DOMAIN      	  : $DOMAIN"
     echo "  Website Root      : $WEBSITE_ROOT_DIR"
@@ -163,7 +163,7 @@ function print_old_config()
 function print_new_config()
 {
     echo 
-    echo "NEW CONFIGURATION"
+    echo "  NEW CONFIGURATION"
     echo 
     echo "  DOMAIN      	  : $NEW_DOMAIN"
     echo "  Website Root      : $NEW_WEBSITE_ROOT_DIR"
@@ -178,7 +178,7 @@ function print_new_config()
 function get_abs_path_new_website_root()
 {
     cd $NEW_WEBSITE_ROOT_DIR
-    [ $? -ne 0 ] && { echo "[ ERROR ] [ ${LINENO} ]"; exit 1; }
+    [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ]"; exit 1; }
     NEW_WEBSITE_ROOT_DIR=`pwd -P`
 }
 
@@ -198,19 +198,21 @@ function importe_database()
 {
     cd $SOURCE_PATH
     mysql -u$NEW_DB_USERNAME  -p$NEW_DB_PASSWORD $NEW_DB_NAME < ${RESTORE_DIR}/db/database.sql
-    [ $? -ne 0 ] && { echo "[ ERROR ] [ ${LINENO} ] Database Import Failed"; exit 1; }
+    [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ] Database Import Failed"; exit 1; }
 }
 
 function importe_code()
 {
     cd $SOURCE_PATH
     mv ${RESTORE_DIR}/code/* ${NEW_WEBSITE_ROOT_DIR}/
-    [ $? -ne 0 ] && { echo "[ ERROR ] [ ${LINENO} ] Website copy failed"; exit 1; }
+    [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ] Website copy failed"; exit 1; }
 }
 
 function migration_success()
 {
-    echo "[ SUCCESS ] website migrated successfully ( $NEW_DOMAIN )"
+    echo
+    echo "  [ SUCCESS ] website migrated successfully ( $NEW_DOMAIN )"
+    echo
 }
 
 
diff --git a/src/restore_website b/src/restore_website
--- a/src/restore_website
+++ b/src/restore_website
@@ -17,9 +17,9 @@ function get_current_dir()
 function arg_check()
 {
     if [ -z "$INPUT" ]; then
-        echo "[ ERROR ] backup file name missing "
+        echo "  [ ERROR ] backup file name missing "
         echo
-        echo "[ EXAMPLE ] ./restore.sh backup.tar.gz"
+        echo "  [ EXAMPLE ] ./restore_website backup.tar.gz"
         echo
         exit 1
     fi
@@ -30,7 +30,7 @@ function db_empty_check()
     table_count=$(mysql -u$DB_USERNAME -p$DB_PASSWORD -h $DB_HOST -P $DB_PORT $DB_NAME -e "SHOW TABLES;" | wc -l)
 
     if [ $table_count -gt 0 ];then
-        echo "[ ERROR ] [ ${LINENO} ] DB is not empty ( table_count : $table_count ), truncate database before restore"
+        echo "  [ ERROR ] [ ${LINENO} ] DB is not empty ( table_count : $table_count ), truncate database before restore"
         echo
         echo "      -> $DB_NAME"
         echo
@@ -43,7 +43,7 @@ function dir_empty_check()
 {
     file_count=`ls ${WEBSITE_ROOT_DIR}/ | wc -l`
     if [ $file_count -gt 0 ];then
-        echo "[ ERROR ] [ ${LINENO} ] website root directory is not empty, clear all files before restoring"
+        echo "  [ ERROR ] [ ${LINENO} ] website root directory is not empty, clear all files before restoring"
         echo
         echo "      -> $WEBSITE_ROOT_DIR"
         echo
@@ -61,11 +61,11 @@ function validate_input()
 
     # GET ABSOLUTE PATH 
     cd $SOURCE_PATH
-    [ $? -ne 0 ] && { echo "[ ERROR ] [ ${LINENO} ]"; exit 1; }
+    [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ]"; exit 1; }
     SOURCE_PATH=`pwd -P`
 
     cd $SOURCE_PATH
-    [ $? -ne 0 ] && { echo "[ ERROR ] [ ${LINENO} ]"; exit 1; }
+    [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ]"; exit 1; }
 
     # EXTRACT FILENAME AND PATH FROM INPUT 
 
@@ -86,13 +86,13 @@ function validate_input()
 
 
     if [ "$EXTN1" != "gz" ]; then
-        echo "[ ERROR ] invalid backup file name ( file name should end with .tar.gz ) "
+        echo "  [ ERROR ] invalid backup file name ( file name should end with .tar.gz ) "
         echo
         exit 1
     fi
 
     if [ "$EXTN2" != "tar" ]; then
-        echo "[ ERROR ] invalid backup file name ( file name should end with .tar.gz ) "
+        echo "  [ ERROR ] invalid backup file name ( file name should end with .tar.gz ) "
         echo
         exit 1
     fi
@@ -116,19 +116,19 @@ function get_user_confirmation()
 function extract_backup_archive()
 {
     echo
-    echo "[ status ] extracting backup file : $SOURCE_FILE"
+    echo "  Extracting backup file : $SOURCE_FILE"
     echo
 
     # Enter backup directory
     cd $SOURCE_PATH
-    [ $? -ne 0 ] && { echo "[ ERROR ] [ ${LINENO} ]"; exit 1; }
+    [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ]"; exit 1; }
 
     # Remove Old Restore Folder ( if any )
     rm -rf $RESTORE_DIR
 
     # Extract backup archive
     tar -zxvf $SOURCE_FILE 1> /dev/null
-    [ $? -ne 0 ] && { echo "[ ERROR ] [ ${LINENO} ]"; exit 1; }
+    [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ]"; exit 1; }
     echo
 }
 
@@ -136,14 +136,14 @@ function extract_backup_archive()
 function import_config()
 {
     source $SOURCE_PATH/$RESTORE_DIR/restore_config.sh
-    [ $? -ne 0 ] && { echo "[ ERROR ] [ ${LINENO} ]"; exit 1; }
+    [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ]"; exit 1; }
 
 }
 
 function print_config()
 {
     echo
-    echo "PREVIOUS SERVER CONFIGURATION"
+    echo "  PREVIOUS SERVER CONFIGURATION"
     echo
     echo "  DOMAIN      	  : $DOMAIN"
     echo "  Website Root      : $WEBSITE_ROOT_DIR"
@@ -154,7 +154,10 @@ function print_config()
     echo "  DB PORT       	  : $DB_PORT"
     echo 
     echo
-    echo " Note: Make sure your existing config is same as above. If not try ( ./migrate.sh $INPUT )"
+    echo "  Note: Make sure your existing config is same as above. If not use the following command,"
+    echo
+    echo "  ./migrate_website $INPUT"
+    echo
     echo
 
 }
@@ -162,7 +165,7 @@ function print_config()
 function get_abs_path_website_root()
 {
     cd $WEBSITE_ROOT_DIR
-    [ $? -ne 0 ] && { echo "[ ERROR ] [ ${LINENO} ]"; exit 1; }
+    [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ]"; exit 1; }
     WEBSITE_ROOT_DIR=`pwd -P`
 }
 
@@ -170,19 +173,21 @@ function importe_database()
 {
     cd $SOURCE_PATH
     mysql -u$DB_USERNAME  -p$DB_PASSWORD $DB_NAME < ${RESTORE_DIR}/db/database.sql
-    [ $? -ne 0 ] && { echo "[ ERROR ] [ ${LINENO} ] Database Import Failed"; exit 1; }
+    [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ] Database Import Failed"; exit 1; }
 }
 
 function importe_code()
 {
     cd $SOURCE_PATH
     mv ${RESTORE_DIR}/code/* ${WEBSITE_ROOT_DIR}/
-    [ $? -ne 0 ] && { echo "[ ERROR ] [ ${LINENO} ] Website copy failed"; exit 1; }
+    [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ] Website copy failed"; exit 1; }
 }
 
 function restore_success()
 {
-    echo "[ SUCCESS ] website restore successfully ( $DOMAIN )"
+    echo
+    echo "  [ SUCCESS ] website restore successfully ( $DOMAIN )"
+    echo
 }
 
 
